export const people = [
  { name: "John", age: 21, nationality: "English" },
  { name: "Maria", age: 30, nationality: "Spanish" },
  { name: "Li Wei", age: 27, nationality: "Chinese" },
  { name: "Olga", age: 25, nationality: "Russian" },
  { name: "Aisha", age: 29, nationality: "Moroccan" },
  { name: "Carlos", age: 33, nationality: "Mexican" },
  { name: "Amir", age: 35, nationality: "Egyptian" },
  { name: "Sophia", age: 22, nationality: "Italian" },
  { name: "David", age: 28, nationality: "American" },
  { name: "Yuki", age: 26, nationality: "Japanese" },
  { name: "Priya", age: 24, nationality: "Indian" },
  { name: "Thiago", age: 31, nationality: "Brazilian" },
  { name: "Anna", age: 27, nationality: "German" },
  { name: "Samantha", age: 32, nationality: "Canadian" },
  { name: "Jorge", age: 34, nationality: "Argentinian" },
  { name: "Elena", age: 23, nationality: "Greek" },
  { name: "Tom", age: 26, nationality: "Australian" },
  { name: "Fatima", age: 28, nationality: "Saudi Arabian" },
  { name: "Jean", age: 29, nationality: "French" },
  { name: "Ahmed", age: 31, nationality: "Pakistani" },
];
